version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/be
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/be
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/app/be/scripts
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/app/be/scripts/*.sh
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 60
      runas: ubuntu
