global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # 백엔드 메트릭
  - job_name: "springboot_"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "host.docker.internal:8080" ]  # Docker 네트워크 내 컨테이너 이름 사용
        labels:
          service: "backend"

  # 프런트 메트릭
  - job_name: "nextjs_"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ "host.docker.internal:3000" ]  # Docker 네트워크 내 컨테이너 이름 사용
        labels:
          service: "frontend"

  # Prometheus 자체 메트릭
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  # Promtail 메트릭 (선택사항)
  - job_name: "promtail-be"
    static_configs:
      - targets: [ "devths-be-promtail:9080" ]
        labels:
          service: "log-collector"
